//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotovBuilder.Shared.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TotovBuilder.Shared.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure blob &quot;{0}&quot; fetched from container &quot;{1}&quot;..
        /// </summary>
        internal static string BlobFetched {
            get {
                return ResourceManager.GetString("BlobFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while fetching Azure blob &quot;{0}&quot; from container &quot;{1}&quot; :
        ///{2}.
        /// </summary>
        internal static string BlobFetchError {
            get {
                return ResourceManager.GetString("BlobFetchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution delay ({0}s) exceeded while fetching Azure blob &quot;{1}&quot; from container &quot;{2}&quot;..
        /// </summary>
        internal static string BlobFetchExecutionDelayExceeded {
            get {
                return ResourceManager.GetString("BlobFetchExecutionDelayExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure blob &quot;{0}&quot; updated in container &quot;{1}&quot;..
        /// </summary>
        internal static string BlobUpdated {
            get {
                return ResourceManager.GetString("BlobUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating Azure blob &quot;{0}&quot; in container &quot;{1}&quot; :
        ///{2}.
        /// </summary>
        internal static string BlobUpdateError {
            get {
                return ResourceManager.GetString("BlobUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution delay ({0}s) exceeded while updating Azure blob &quot;{1}&quot; in container &quot;{2}&quot;..
        /// </summary>
        internal static string BlobUpdateExecutionDelayExceeded {
            get {
                return ResourceManager.GetString("BlobUpdateExecutionDelayExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure container &quot;{0}&quot; updated..
        /// </summary>
        internal static string ContainerUpdated {
            get {
                return ResourceManager.GetString("ContainerUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating Azure container &quot;{0}&quot; :
        ///{1}.
        /// </summary>
        internal static string ContainerUpdateError {
            get {
                return ResourceManager.GetString("ContainerUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting Azure blob &quot;{0}&quot; from container &quot;{1}&quot;..
        /// </summary>
        internal static string DeletingBlob {
            get {
                return ResourceManager.GetString("DeletingBlob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching Azure blob &quot;{0}&quot; in container &quot;{1}&quot;..
        /// </summary>
        internal static string FetchingBlob {
            get {
                return ResourceManager.GetString("FetchingBlob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration for connecting to Azure blob storage :
        ///- Connection string : &quot;{0}&quot;,
        ///- Execution timeout : {1},
        ///- Container name : &quot;{2}&quot;.
        /// </summary>
        internal static string InvalidConfiguration {
            get {
                return ResourceManager.GetString("InvalidConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Azure blob &quot;{0}&quot; in container &quot;{1}&quot;..
        /// </summary>
        internal static string UpdatingBlob {
            get {
                return ResourceManager.GetString("UpdatingBlob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Azure container &quot;{0}&quot;..
        /// </summary>
        internal static string UpdatingContainer {
            get {
                return ResourceManager.GetString("UpdatingContainer", resourceCulture);
            }
        }
    }
}
