//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotovBuilder.Shared.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TotovBuilder.Shared.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting blob &quot;{0}&quot; from container &quot;{1}&quot;..
        /// </summary>
        internal static string BlobDeleting {
            get {
                return ResourceManager.GetString("BlobDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob &quot;{0}&quot; fetched from container &quot;{1}&quot;..
        /// </summary>
        internal static string BlobFetched {
            get {
                return ResourceManager.GetString("BlobFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching blob &quot;{0}&quot; in container &quot;{1}&quot;..
        /// </summary>
        internal static string BlobFetching {
            get {
                return ResourceManager.GetString("BlobFetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while fetching Azure blob &quot;{0}&quot; from container &quot;{1}&quot; :
        ///{2}.
        /// </summary>
        internal static string BlobFetchingError {
            get {
                return ResourceManager.GetString("BlobFetchingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob &quot;{0}&quot; updated in container &quot;{1}&quot;..
        /// </summary>
        internal static string BlobUpdated {
            get {
                return ResourceManager.GetString("BlobUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating blob &quot;{0}&quot; in container &quot;{1}&quot;..
        /// </summary>
        internal static string BlobUpdating {
            get {
                return ResourceManager.GetString("BlobUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating Azure blob &quot;{0}&quot; in container &quot;{1}&quot; :
        ///{2}.
        /// </summary>
        internal static string BlobUpdatingError {
            get {
                return ResourceManager.GetString("BlobUpdatingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container &quot;{0}&quot; updated..
        /// </summary>
        internal static string ContainerUpdated {
            get {
                return ResourceManager.GetString("ContainerUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating container &quot;{0}&quot;..
        /// </summary>
        internal static string ContainerUpdating {
            get {
                return ResourceManager.GetString("ContainerUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating Azure container&quot;{0}&quot; :
        ///{1}.
        /// </summary>
        internal static string ContainerUpdatingError {
            get {
                return ResourceManager.GetString("ContainerUpdatingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution delay exceeded..
        /// </summary>
        internal static string ExecutionDelayExceeded {
            get {
                return ResourceManager.GetString("ExecutionDelayExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration for connecting to Azure blob storage :
        ///- Connection string : &quot;{0}&quot;,
        ///- Execution timeout : {1},
        ///- Container name : &quot;{2}&quot;.
        /// </summary>
        internal static string InvalidConfiguration {
            get {
                return ResourceManager.GetString("InvalidConfiguration", resourceCulture);
            }
        }
    }
}
